[project]
name = "pdfmod"
version = "0.1.0"
description = "A command-line utility for modifying PDFs with ease. Perform common PDF operations such as merging, splitting, compressing, and extracting pages, all from your terminal."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.25.3",
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
]

[tool.ruff]
line-length = 100
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
