name: Release

on:
  push:
    tags:
      - v*

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project -p 3.11 --with dist/*.whl tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project -p 3.11 --with dist/*.tar.gz tests/smoke_test.py
      - run: uv publish --trusted-publishing always
